<table class="tbody" cellspacing="1" align="center" cellpadding="0">
    <tr>
        <td class="thead">
            &nbsp; <img src="images/tb_title.gif" align="absmiddle"> &nbsp;訪問者瀏覽器及數量
        </td>
    </tr>
    <tr>
        <td class="middle">

        <table border="0" cellpadding="0" cellspacing="0" width="100%" align="center">
        <tr height="9"><td colspan="2"></td></tr>
        <tr height="10">
            <td></td>
            <td><img src="images/h_top.gif"></td>
        </tr>
        <?php foreach ($browserlist as $value) { ?>
        <tr>
            <td style="padding-left: 20px">
                <span style="cursor: default" title="<?= $value['whichbrowser'] ?><br>
訪問 <?= $value['visittimes'] ?> 次, <?= $value['percent'] ?>"><?= $value['whichbrowser'] ?></span>
            </td>
            <td class="hback" align="left" style="background: url('images/h_back.gif') repeat-y;">
                <img src="images/h_bar.gif"
                    width="<?= $value['height'] ?>" height="11"
                    alt="<?= $value['whichbrowser'] ?><br>
訪問 <?= $value['visittimes'] ?> 次, <?= $value['percent'] ?>">
                <span style="font-family:Arial; letter-spacing:-1"><?= $value['visittimes'] ?></span>
            </td>
        <tr>
        <?php } ?>
        <tr height="10">
            <td></td>
            <td><img src="images/h_bottom.gif"></td>
        </tr>
        <tr height="5"><td colspan="2"></td></tr>

        </table>


        </td>
    </tr>
</table>

<br>

