<br>
<table cellpadding="2" cellspacing="0" border="0" align="center">
    <tr>
        <td align="center" style="font-size:8pt">
            TCBB Stat System version 2.0 <br>
            Copyright &copy; ITS - <a class="c1" href="http://www.bbsfans.com" target="_blank">BBSFans.com</a>, 2002. All rights reserved
        </td>
    </tr>
    <tr height="1" style="background-color: #000000">
        <td></td>
    </tr>
    <tr>
        <td align="center" style="font-size:8pt">
            統計服務提供: <a class="c1" href="<?= $conf['service_link'] ?>" target="_blank"><?= $conf['service_offer'] ?></a>&nbsp;&nbsp;&nbsp;&nbsp;
            技術支持: <a class="c1" href="http://www.bbsfans.com" target="_blank">BBSFans.com</a>
        </td>
    </tr>
</table>
